---
- name: Destroy
  hosts: localhost
  gather_facts: false
  no_log: "{{ molecule_no_log }}"

  tasks:
    - name: Prepare VMs config
      block:
        - name: Prepare VMs config
          ansible.builtin.set_fact:
            instance_conf: "{{ lookup('file', molecule_instance_config) | from_yaml }}"
      rescue:
        - name: Prepare VMs config when file missing
          ansible.builtin.set_fact:
            instance_conf: {}

    - name: Read PID files
      ansible.builtin.set_fact:
        pid: "{{ lookup('file', item.pidfile) }}"
      loop: "{{ instance_conf }}"
      loop_control:
        label: "{{ item.name }}"
      register: qemu_processes

    - debug: var=qemu_processes

    - name: Destroy running VMs
      ansible.builtin.shell: "kill {{ item.ansible_facts.pid }}"
      loop: "{{ qemu_processes.results }}"
      loop_control:
        label: "{{ item.item.name }}"

    - name: Prepare VMs config list
      ansible.builtin.set_fact:
        instance_conf: {}

    - name: Dump VMs config
      ansible.builtin.copy:
        content: "{{ instance_conf | to_json | from_json | to_yaml }}"
        dest: "{{ molecule_instance_config }}"
        mode: "0644"
